{
 "title": "Taxi price",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Current prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Prices",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "query": "from(bucket:\"raccoon\")\n    |> range(start: -24h)\n    |> group(columns: [\"routeName\"])\n    |> last()\n"
    }
   ]
  },
  { "title": "Last 24h", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Taxi price for last 24h",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "query": "from(bucket:\"raccoon\")\n    |> range(start: -24h)\n"
    }
   ]
  },
  {
   "title": "Avg price by route for last 24h",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "query": "from(bucket:\"raccoon\")\n    |> range(start: -24h)\n    |> group(columns: [\"routeName\"])\n    |> aggregateWindow(every: 1h, fn:mean)\n"
    }
   ]
  },
  { "title": "Last week", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Avg routes price by week days",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\n\nweekDays = [0:\"Sunday\",1:\"Monday\",2:\"Tuesday\",3:\"Wednesday\",4:\"Thursday\",5:\"Friday\",6:\"Saturday\"]\n\nfrom(bucket: \"raccoon\")\n  |> range(start: -1w)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"taxi-price\")\n  |> group(columns: [\"routeName\"])\n  |> aggregateWindow(every: 1d, fn: mean)\n  |> truncateTimeColumn(unit: 1d)\n  |> map(fn: (r) => ({ r with\n    weekDay:\n      dict.get(dict: weekDays, key:date.weekDay(t: r._time), default: \"\")\n  }))\n"
    }
   ]
  }
 ]
}